// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAttachmentFromBytes(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAttachmentFromBytes'](arg1, arg2, arg3, arg4);
}

export function AddAttachmentFromFile(arg1, arg2) {
  return window['go']['main']['App']['AddAttachmentFromFile'](arg1, arg2);
}

export function Catalog(arg1) {
  return window['go']['main']['App']['Catalog'](arg1);
}

export function CommitNoteBody(arg1) {
  return window['go']['main']['App']['CommitNoteBody'](arg1);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function CreateManualBackup(arg1) {
  return window['go']['main']['App']['CreateManualBackup'](arg1);
}

export function CreateNote(arg1, arg2) {
  return window['go']['main']['App']['CreateNote'](arg1, arg2);
}

export function CreateNotebook(arg1, arg2) {
  return window['go']['main']['App']['CreateNotebook'](arg1, arg2);
}

export function CreateSavedSearch(arg1, arg2) {
  return window['go']['main']['App']['CreateSavedSearch'](arg1, arg2);
}

export function CreateTag(arg1) {
  return window['go']['main']['App']['CreateTag'](arg1);
}

export function DefaultDatabasePath() {
  return window['go']['main']['App']['DefaultDatabasePath']();
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function DeleteSavedSearch(arg1) {
  return window['go']['main']['App']['DeleteSavedSearch'](arg1);
}

export function DiffRevisions(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiffRevisions'](arg1, arg2, arg3);
}

export function EnsureDailyBackup(arg1) {
  return window['go']['main']['App']['EnsureDailyBackup'](arg1);
}

export function ExportNotes(arg1, arg2) {
  return window['go']['main']['App']['ExportNotes'](arg1, arg2);
}

export function GetNote(arg1) {
  return window['go']['main']['App']['GetNote'](arg1);
}

export function GetNoteDocument(arg1) {
  return window['go']['main']['App']['GetNoteDocument'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportBerestaArchive(arg1) {
  return window['go']['main']['App']['ImportBerestaArchive'](arg1);
}

export function ImportEvernoteArchive(arg1) {
  return window['go']['main']['App']['ImportEvernoteArchive'](arg1);
}

export function ListBackups(arg1) {
  return window['go']['main']['App']['ListBackups'](arg1);
}

export function ListNoteAttachments(arg1) {
  return window['go']['main']['App']['ListNoteAttachments'](arg1);
}

export function ListNotebooks() {
  return window['go']['main']['App']['ListNotebooks']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function ListRevisions(arg1) {
  return window['go']['main']['App']['ListRevisions'](arg1);
}

export function ListSavedSearches() {
  return window['go']['main']['App']['ListSavedSearches']();
}

export function ListTags() {
  return window['go']['main']['App']['ListTags']();
}

export function LockAccount() {
  return window['go']['main']['App']['LockAccount']();
}

export function MoveNotebook(arg1, arg2) {
  return window['go']['main']['App']['MoveNotebook'](arg1, arg2);
}

export function PickAttachmentFile() {
  return window['go']['main']['App']['PickAttachmentFile']();
}

export function PickExportDestination() {
  return window['go']['main']['App']['PickExportDestination']();
}

export function PickImportSource(arg1) {
  return window['go']['main']['App']['PickImportSource'](arg1);
}

export function PickSaveDestination(arg1) {
  return window['go']['main']['App']['PickSaveDestination'](arg1);
}

export function PlanRestore(arg1, arg2) {
  return window['go']['main']['App']['PlanRestore'](arg1, arg2);
}

export function PreviewBackup(arg1) {
  return window['go']['main']['App']['PreviewBackup'](arg1);
}

export function ReadAttachmentPreview(arg1) {
  return window['go']['main']['App']['ReadAttachmentPreview'](arg1);
}

export function RemoveAttachment(arg1, arg2) {
  return window['go']['main']['App']['RemoveAttachment'](arg1, arg2);
}

export function RenameNotebook(arg1, arg2) {
  return window['go']['main']['App']['RenameNotebook'](arg1, arg2);
}

export function RestoreNote(arg1) {
  return window['go']['main']['App']['RestoreNote'](arg1);
}

export function RestoreRevision(arg1, arg2) {
  return window['go']['main']['App']['RestoreRevision'](arg1, arg2);
}

export function RestoreSelective(arg1, arg2, arg3) {
  return window['go']['main']['App']['RestoreSelective'](arg1, arg2, arg3);
}

export function RestoreWhole(arg1, arg2) {
  return window['go']['main']['App']['RestoreWhole'](arg1, arg2);
}

export function RevisionMarkdown(arg1, arg2) {
  return window['go']['main']['App']['RevisionMarkdown'](arg1, arg2);
}

export function RunGarbageCollection(arg1) {
  return window['go']['main']['App']['RunGarbageCollection'](arg1);
}

export function SaveAttachmentToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveAttachmentToFile'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function SearchByTag(arg1) {
  return window['go']['main']['App']['SearchByTag'](arg1);
}

export function SetNoteFlags(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNoteFlags'](arg1, arg2, arg3);
}

export function SetNoteNotebook(arg1, arg2) {
  return window['go']['main']['App']['SetNoteNotebook'](arg1, arg2);
}

export function SetNoteTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNoteTag'](arg1, arg2, arg3);
}

export function SetNotebookDeleted(arg1, arg2) {
  return window['go']['main']['App']['SetNotebookDeleted'](arg1, arg2);
}

export function SetTagDeleted(arg1, arg2) {
  return window['go']['main']['App']['SetTagDeleted'](arg1, arg2);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function SyncStatus() {
  return window['go']['main']['App']['SyncStatus']();
}

export function UnlockAccount(arg1) {
  return window['go']['main']['App']['UnlockAccount'](arg1);
}

export function UpdateSavedSearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSavedSearch'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function VerifyAllBackups() {
  return window['go']['main']['App']['VerifyAllBackups']();
}

export function VerifyBackup(arg1) {
  return window['go']['main']['App']['VerifyBackup'](arg1);
}
