// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddAttachmentFromFile(arg1:string,arg2:string):Promise<main.AttachmentDTO>;

export function Catalog(arg1:string):Promise<main.LocaleCatalog>;

export function CommitNoteBody(arg1:main.CommitNoteBodyRequest):Promise<void>;

export function CreateAccount(arg1:main.CreateAccountRequest):Promise<main.AccountInfo>;

export function CreateManualBackup(arg1:string):Promise<main.BackupDTO>;

export function CreateNote(arg1:string,arg2:string):Promise<main.NoteDTO>;

export function CreateNotebook(arg1:string,arg2:string):Promise<main.NotebookDTO>;

export function CreateSavedSearch(arg1:string,arg2:string):Promise<main.SavedSearchDTO>;

export function CreateTag(arg1:string):Promise<main.TagDTO>;

export function DefaultDatabasePath():Promise<string>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteSavedSearch(arg1:string):Promise<void>;

export function DiffRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<main.DiffLineDTO>>;

export function EnsureDailyBackup(arg1:string):Promise<boolean>;

export function ExportNotes(arg1:string,arg2:Array<string>):Promise<main.ExportManifestDTO>;

export function GetNote(arg1:string):Promise<main.NoteDTO>;

export function GetSettings():Promise<main.AppSettings>;

export function ImportBerestaArchive(arg1:string):Promise<main.ImportResultDTO>;

export function ImportEvernoteArchive(arg1:string):Promise<main.ImportResultDTO>;

export function ListBackups(arg1:string):Promise<Array<main.BackupDTO>>;

export function ListNotebooks():Promise<Array<main.NotebookDTO>>;

export function ListNotes():Promise<Array<main.NoteDTO>>;

export function ListRevisions(arg1:string):Promise<Array<main.RevisionDTO>>;

export function ListSavedSearches():Promise<Array<main.SavedSearchDTO>>;

export function ListTags():Promise<Array<main.TagDTO>>;

export function LockAccount():Promise<void>;

export function MoveNotebook(arg1:string,arg2:string):Promise<void>;

export function PickAttachmentFile():Promise<string>;

export function PickExportDestination():Promise<string>;

export function PickImportSource(arg1:string):Promise<string>;

export function PickSaveDestination(arg1:string):Promise<string>;

export function PlanRestore(arg1:string,arg2:Array<string>):Promise<main.RestorePlanDTO>;

export function PreviewBackup(arg1:string):Promise<main.BackupPreviewDTO>;

export function RemoveAttachment(arg1:string,arg2:string):Promise<void>;

export function RenameNotebook(arg1:string,arg2:string):Promise<void>;

export function RestoreNote(arg1:string):Promise<void>;

export function RestoreRevision(arg1:string,arg2:string):Promise<void>;

export function RestoreSelective(arg1:string,arg2:Array<string>,arg3:string):Promise<main.RestoreResultDTO>;

export function RestoreWhole(arg1:string,arg2:string):Promise<main.RestoreResultDTO>;

export function RevisionMarkdown(arg1:string,arg2:string):Promise<string>;

export function RunGarbageCollection(arg1:boolean):Promise<main.GCReportDTO>;

export function SaveAttachmentToFile(arg1:string,arg2:string):Promise<main.AttachmentSaveResult>;

export function Search(arg1:string):Promise<Array<main.SearchResultDTO>>;

export function SetNoteFlags(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SetNoteNotebook(arg1:string,arg2:string):Promise<void>;

export function SetNoteTag(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetNotebookDeleted(arg1:string,arg2:boolean):Promise<void>;

export function SetTagDeleted(arg1:string,arg2:boolean):Promise<void>;

export function Status():Promise<main.AccountStatus>;

export function SyncStatus():Promise<string>;

export function UnlockAccount(arg1:main.UnlockAccountRequest):Promise<main.AccountInfo>;

export function UpdateSavedSearch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function VerifyAllBackups():Promise<void>;

export function VerifyBackup(arg1:string):Promise<void>;
