// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {transport} from '../models';

export function AcceptWorkspaceGrant(arg1:string):Promise<main.WorkspaceSummaryDTO>;

export function AddAttachmentFromBytes(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.AttachmentDTO>;

export function AddAttachmentFromFile(arg1:string,arg2:string):Promise<main.AttachmentDTO>;

export function AutostartStatus():Promise<main.AutostartStatusDTO>;

export function Catalog(arg1:string):Promise<main.LocaleCatalog>;

export function CommitNoteBody(arg1:main.CommitNoteBodyRequest):Promise<void>;

export function ConnectServer(arg1:main.ConnectServerRequest):Promise<main.ServerConnectionInfo>;

export function CreateAccount(arg1:main.CreateAccountRequest):Promise<main.AccountInfo>;

export function CreateManualBackup(arg1:string):Promise<main.BackupDTO>;

export function CreateNote(arg1:string,arg2:string):Promise<main.NoteDTO>;

export function CreateNotebook(arg1:string,arg2:string):Promise<main.NotebookDTO>;

export function CreateSavedSearch(arg1:string,arg2:string):Promise<main.SavedSearchDTO>;

export function CreateTag(arg1:string):Promise<main.TagDTO>;

export function DefaultDatabasePath():Promise<string>;

export function DeleteNote(arg1:string):Promise<void>;

export function DeleteSavedSearch(arg1:string):Promise<void>;

export function DiagnoseServer():Promise<transport.Diagnostics>;

export function DiffRevisions(arg1:string,arg2:string,arg3:string):Promise<Array<main.DiffLineDTO>>;

export function DisableServer():Promise<void>;

export function EnsureDailyBackup(arg1:string):Promise<boolean>;

export function ExportIdentity():Promise<string>;

export function ExportNotes(arg1:string,arg2:Array<string>):Promise<main.ExportManifestDTO>;

export function GetNote(arg1:string):Promise<main.NoteDTO>;

export function GetNoteDocument(arg1:string):Promise<main.NoteDocumentDTO>;

export function GetSettings():Promise<main.AppSettings>;

export function ImportBerestaArchive(arg1:string):Promise<main.ImportResultDTO>;

export function ImportEvernoteArchive(arg1:string):Promise<main.ImportResultDTO>;

export function ListBackups(arg1:string):Promise<Array<main.BackupDTO>>;

export function ListNoteAttachments(arg1:string):Promise<Array<main.AttachmentDTO>>;

export function ListNotebooks():Promise<Array<main.NotebookDTO>>;

export function ListNotes():Promise<Array<main.NoteDTO>>;

export function ListRevisions(arg1:string):Promise<Array<main.RevisionDTO>>;

export function ListSavedSearches():Promise<Array<main.SavedSearchDTO>>;

export function ListSyncDevices():Promise<Array<transport.RemoteDevice>>;

export function ListSyncQuarantine():Promise<Array<main.SyncQuarantineDTO>>;

export function ListTags():Promise<Array<main.TagDTO>>;

export function ListWorkspaceMembers(arg1:string):Promise<Array<main.WorkspaceMemberDTO>>;

export function ListWorkspaces():Promise<Array<main.WorkspaceSummaryDTO>>;

export function LockAccount():Promise<void>;

export function MoveNotebook(arg1:string,arg2:string):Promise<void>;

export function NoteTagsByWorkspace():Promise<Record<string, Array<string>>>;

export function PickAttachmentFile():Promise<string>;

export function PickBackupDirectory():Promise<string>;

export function PickExportDestination():Promise<string>;

export function PickImportSource(arg1:string):Promise<string>;

export function PickSaveDestination(arg1:string):Promise<string>;

export function PlanRestore(arg1:string,arg2:Array<string>):Promise<main.RestorePlanDTO>;

export function PreviewBackup(arg1:string):Promise<main.BackupPreviewDTO>;

export function ReadAttachmentPreview(arg1:string):Promise<main.AttachmentPreviewDTO>;

export function RemoveAttachment(arg1:string,arg2:string):Promise<void>;

export function RenameNotebook(arg1:string,arg2:string):Promise<void>;

export function RestoreNote(arg1:string):Promise<void>;

export function RestoreRevision(arg1:string,arg2:string):Promise<void>;

export function RestoreSelective(arg1:string,arg2:Array<string>,arg3:string):Promise<main.RestoreResultDTO>;

export function RestoreWhole(arg1:string,arg2:string):Promise<main.RestoreResultDTO>;

export function RetrySyncQuarantine(arg1:string):Promise<void>;

export function RevisionMarkdown(arg1:string,arg2:string):Promise<string>;

export function RevokeSyncDevice(arg1:string):Promise<void>;

export function RevokeWorkspaceMember(arg1:string,arg2:string):Promise<void>;

export function RunGarbageCollection(arg1:boolean):Promise<main.GCReportDTO>;

export function SaveAttachmentToFile(arg1:string,arg2:string):Promise<main.AttachmentSaveResult>;

export function Search(arg1:string):Promise<Array<main.SearchResultDTO>>;

export function SearchByTag(arg1:string):Promise<Array<main.SearchResultDTO>>;

export function SetActiveWorkspace(arg1:string):Promise<void>;

export function SetNoteFlags(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function SetNoteNotebook(arg1:string,arg2:string):Promise<void>;

export function SetNoteTag(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SetNotebookDeleted(arg1:string,arg2:boolean):Promise<void>;

export function SetTagDeleted(arg1:string,arg2:boolean):Promise<void>;

export function ShareWorkspace(arg1:string):Promise<string>;

export function Status():Promise<main.AccountStatus>;

export function SyncConnectionInfo():Promise<main.ServerConnectionInfo>;

export function SyncError():Promise<string>;

export function SyncNow():Promise<void>;

export function SyncStatus():Promise<string>;

export function UnlockAccount(arg1:main.UnlockAccountRequest):Promise<main.AccountInfo>;

export function UpdateSavedSearch(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateSettings(arg1:main.AppSettings):Promise<main.AppSettings>;

export function VerifyAllBackups():Promise<void>;

export function VerifyBackup(arg1:string):Promise<void>;

export function WipeLocalAccount(arg1:string):Promise<void>;
