class Strings {
  Strings(this.language);

  final String language;

  static const values = <String, Map<String, String>>{
    "en": {
      "tagline": "Encrypted notes, available offline.",
      "create": "Create local account",
      "unlock": "Unlock",
      "passphrase": "Passphrase",
      "local_hint":
          "Your account starts only on this device. A server is optional.",
      "notes": "Notes",
      "notebooks": "Notebooks",
      "tags": "Tags",
      "search": "Search notes and filters",
      "new_note": "New note",
      "save": "Save",
      "preview": "Preview",
      "edit": "Edit",
      "photo": "Add photo",
      "revisions": "Revisions",
      "restore": "Restore",
      "sync": "Sync now",
      "server": "Synchronization server",
      "server_optional":
          "Optional. Your complete collection stays on this device.",
      "server_url": "HTTPS server URL",
      "invite_code": "Invite code (first connection)",
      "fingerprint": "SHA-256 certificate fingerprint",
      "pinned": "Pinned certificate",
      "trusted": "System-trusted certificate",
      "connect": "Connect",
      "disconnect": "Disable server",
      "lock": "Lock",
      "offline": "Changes save locally and will sync later.",
      "empty": "No notes yet",
      "title": "Title",
      "body": "Markdown body",
      "error": "Could not complete the action",
      "backup": "Encrypted backup",
      "backup_now": "Back up now",
      "backup_destination": "Choose destination",
      "backup_import": "Import from destination",
      "backup_empty": "No backups yet",
      "replace_restore": "Replace from backup",
      "restore_warning":
          "This verifies the backup, creates a safety backup, and replaces the local collection.",
      "cancel": "Cancel",
      "settings": "Settings",
      "auto_lock": "Automatic lock",
      "attachment_retention": "Downloaded attachments",
      "retention_all": "Keep all",
      "retention_selected": "Selected notebooks",
      "retention_metadata": "Metadata only",
      "cache_limit": "Cache limit (MiB)",
      "backup_capacity":
          "Not enough free space. Existing backups were not changed.",
    },
    "ru": {
      "tagline": "Зашифрованные заметки доступны офлайн.",
      "create": "Создать локальный аккаунт",
      "unlock": "Разблокировать",
      "passphrase": "Парольная фраза",
      "local_hint":
          "Аккаунт создаётся только на этом устройстве. Сервер необязателен.",
      "notes": "Заметки",
      "notebooks": "Блокноты",
      "tags": "Метки",
      "search": "Поиск заметок и фильтры",
      "new_note": "Новая заметка",
      "save": "Сохранить",
      "preview": "Просмотр",
      "edit": "Правка",
      "photo": "Добавить фото",
      "revisions": "Версии",
      "restore": "Восстановить",
      "sync": "Синхронизировать",
      "server": "Сервер синхронизации",
      "server_optional":
          "Необязательно. Полная коллекция останется на этом устройстве.",
      "server_url": "HTTPS-адрес сервера",
      "invite_code": "Код приглашения (первое подключение)",
      "fingerprint": "SHA-256 отпечаток сертификата",
      "pinned": "Закреплённый сертификат",
      "trusted": "Доверенный системой сертификат",
      "connect": "Подключить",
      "disconnect": "Отключить сервер",
      "lock": "Заблокировать",
      "offline": "Изменения сохранятся локально и синхронизируются позже.",
      "empty": "Заметок пока нет",
      "title": "Заголовок",
      "body": "Текст Markdown",
      "error": "Не удалось выполнить действие",
      "backup": "Зашифрованная копия",
      "backup_now": "Создать копию",
      "backup_destination": "Выбрать хранилище",
      "backup_import": "Импортировать из хранилища",
      "backup_empty": "Копий пока нет",
      "replace_restore": "Заменить из копии",
      "restore_warning":
          "Копия будет проверена, затем Береста создаст страховочную копию и заменит локальную коллекцию.",
      "cancel": "Отмена",
      "settings": "Настройки",
      "auto_lock": "Автоматическая блокировка",
      "attachment_retention": "Загруженные вложения",
      "retention_all": "Хранить все",
      "retention_selected": "Выбранные блокноты",
      "retention_metadata": "Только метаданные",
      "cache_limit": "Лимит кэша (МиБ)",
      "backup_capacity":
          "Недостаточно свободного места. Существующие копии не изменены.",
    },
  };

  String call(String key) =>
      values[language]?[key] ?? values["en"]![key] ?? key;
}
