class Strings {
  Strings(this.language);

  final String language;

  static const values = <String, Map<String, String>>{
    "en": {
      "tagline": "Encrypted notes, available offline.",
      "create": "Create local account",
      "unlock": "Unlock",
      "passphrase": "Passphrase",
      "local_hint":
          "Your account starts only on this device. A server is optional.",
      "returning_hint": "Enter your passphrase to unlock this device.",
      "notes": "Notes",
      "notebooks": "Notebooks",
      "new_notebook": "New notebook",
      "notebook_name": "Notebook name",
      "delete": "Delete",
      "delete_notebook": "Delete notebook?",
      "delete_notebook_warning":
          "Its notes are kept and stay visible under \"Notes\".",
      "notebook_has_children": "Delete or move its sub-notebooks first.",
      "tags": "Tags",
      "new_tag": "New tag",
      "tag_name": "Tag name",
      "add_tag": "Add tag",
      "move_to_notebook": "Move to notebook",
      "no_notebook": "No notebook",
      "delete_photo": "Delete this photo?",
      "search": "Search notes and filters",
      "new_note": "New note",
      "save": "Save",
      "preview": "Preview",
      "edit": "Edit",
      "photo": "Add photo",
      "revisions": "Revisions",
      "restore": "Restore",
      "sync": "Sync now",
      "server": "Synchronization server",
      "server_optional":
          "Optional. Your complete collection stays on this device.",
      "server_url": "HTTPS server URL",
      "invite_code": "Invite code (first connection)",
      "fingerprint": "SHA-256 certificate fingerprint",
      "pinned": "Pinned certificate",
      "trusted": "System-trusted certificate",
      "connect": "Connect",
      "disconnect": "Disable server",
      "your_identity": "Your identity code",
      "your_identity_hint":
          "Send this code to the owner of a workspace you want to join.",
      "copy": "Copy",
      "copied": "Copied",
      "share_workspace": "Share this workspace",
      "paste_identity": "Paste their identity code",
      "generate_share_code": "Generate share code",
      "grant_code": "Grant code",
      "grant_code_hint": "Send this code back to them so they can join.",
      "join_workspace": "Join a shared workspace",
      "paste_grant": "Paste their grant code",
      "join": "Join workspace",
      "lock": "Lock",
      "offline": "Changes save locally and will sync later.",
      "empty": "No notes yet",
      "title": "Title",
      "body": "Markdown body",
      "error": "Could not complete the action",
      "backup": "Encrypted backup",
      "backup_now": "Back up now",
      "backup_destination": "Choose destination",
      "backup_import": "Import from destination",
      "backup_empty": "No backups yet",
      "replace_restore": "Replace from backup",
      "restore_warning":
          "This verifies the backup, creates a safety backup, and replaces the local collection.",
      "cancel": "Cancel",
      "settings": "Settings",
      "auto_lock": "Automatic lock",
      "attachment_retention": "Downloaded attachments",
      "retention_all": "Keep all",
      "retention_selected": "Selected notebooks",
      "retention_metadata": "Metadata only",
      "cache_limit": "Cache limit (MiB)",
      "backup_capacity":
          "Not enough free space. Existing backups were not changed.",
    },
    "ru": {
      "tagline": "Зашифрованные заметки доступны офлайн.",
      "create": "Создать локальный аккаунт",
      "unlock": "Разблокировать",
      "passphrase": "Парольная фраза",
      "local_hint":
          "Аккаунт создаётся только на этом устройстве. Сервер необязателен.",
      "returning_hint":
          "Введите парольную фразу, чтобы разблокировать это устройство.",
      "notes": "Заметки",
      "notebooks": "Блокноты",
      "new_notebook": "Новый блокнот",
      "notebook_name": "Название блокнота",
      "delete": "Удалить",
      "delete_notebook": "Удалить блокнот?",
      "delete_notebook_warning":
          "Заметки внутри сохранятся и останутся видны в общем списке.",
      "notebook_has_children":
          "Сначала удалите или перенесите вложенные блокноты.",
      "tags": "Метки",
      "new_tag": "Новая метка",
      "tag_name": "Название метки",
      "add_tag": "Добавить метку",
      "move_to_notebook": "Переместить в блокнот",
      "no_notebook": "Без блокнота",
      "delete_photo": "Удалить это фото?",
      "search": "Поиск заметок и фильтры",
      "new_note": "Новая заметка",
      "save": "Сохранить",
      "preview": "Просмотр",
      "edit": "Правка",
      "photo": "Добавить фото",
      "revisions": "Версии",
      "restore": "Восстановить",
      "sync": "Синхронизировать",
      "server": "Сервер синхронизации",
      "server_optional":
          "Необязательно. Полная коллекция останется на этом устройстве.",
      "server_url": "HTTPS-адрес сервера",
      "invite_code": "Код приглашения (первое подключение)",
      "fingerprint": "SHA-256 отпечаток сертификата",
      "pinned": "Закреплённый сертификат",
      "trusted": "Доверенный системой сертификат",
      "connect": "Подключить",
      "disconnect": "Отключить сервер",
      "your_identity": "Ваш код идентификации",
      "your_identity_hint":
          "Отправьте этот код владельцу пространства, к которому хотите присоединиться.",
      "copy": "Копировать",
      "copied": "Скопировано",
      "share_workspace": "Поделиться этим пространством",
      "paste_identity": "Вставьте их код идентификации",
      "generate_share_code": "Создать код доступа",
      "grant_code": "Код доступа",
      "grant_code_hint":
          "Отправьте этот код обратно, чтобы они могли присоединиться.",
      "join_workspace": "Присоединиться к общему пространству",
      "paste_grant": "Вставьте их код доступа",
      "join": "Присоединиться",
      "lock": "Заблокировать",
      "offline": "Изменения сохранятся локально и синхронизируются позже.",
      "empty": "Заметок пока нет",
      "title": "Заголовок",
      "body": "Текст Markdown",
      "error": "Не удалось выполнить действие",
      "backup": "Зашифрованная копия",
      "backup_now": "Создать копию",
      "backup_destination": "Выбрать хранилище",
      "backup_import": "Импортировать из хранилища",
      "backup_empty": "Копий пока нет",
      "replace_restore": "Заменить из копии",
      "restore_warning":
          "Копия будет проверена, затем Береста создаст страховочную копию и заменит локальную коллекцию.",
      "cancel": "Отмена",
      "settings": "Настройки",
      "auto_lock": "Автоматическая блокировка",
      "attachment_retention": "Загруженные вложения",
      "retention_all": "Хранить все",
      "retention_selected": "Выбранные блокноты",
      "retention_metadata": "Только метаданные",
      "cache_limit": "Лимит кэша (МиБ)",
      "backup_capacity":
          "Недостаточно свободного места. Существующие копии не изменены.",
    },
  };

  String call(String key) =>
      values[language]?[key] ?? values["en"]![key] ?? key;
}
