class Strings {
  Strings(this.language);

  final String language;

  static const values = <String, Map<String, String>>{
    "en": {
      "tagline": "Encrypted notes, available offline.",
      "create": "Create local account",
      "unlock": "Unlock",
      "passphrase": "Passphrase",
      "device_unlock": "Unlock with biometrics or PIN",
      "local_hint":
          "Your account starts only on this device. A server is optional.",
      "returning_hint": "Enter your passphrase to unlock this device.",
      "sync_prompt_title": "Connect to a sync server?",
      "sync_prompt_description":
          "You can connect this device to a self-hosted sync server now, or skip this and do it later from Settings — your local notes are unaffected either way.",
      "sync_prompt_connect": "Connect now",
      "sync_prompt_skip": "Skip for now",
      "notes": "Notes",
      "notebooks": "Notebooks",
      "new_notebook": "New notebook",
      "more_actions": "More actions",
      "notebook_name": "Notebook name",
      "create_action": "Create",
      "rename": "Rename",
      "rename_notebook": "Rename notebook",
      "delete": "Delete",
      "delete_notebook": "Delete notebook?",
      "delete_notebook_warning":
          "Its notes are kept and stay visible under \"Notes\".",
      "notebook_has_children": "Delete or move its sub-notebooks first.",
      "tags": "Tags",
      "new_tag": "New tag",
      "tag_name": "Tag name",
      "add_tag": "Add tag",
      "move_to_notebook": "Move to notebook",
      "no_notebook": "No notebook",
      "delete_photo": "Delete this photo?",
      "delete_attachment": "Delete this attachment?",
      "search": "Search notes and filters",
      "new_note": "New note",
      "untitled": "Untitled",
      "save": "Save",
      "save_state_saving": "Saving…",
      "save_state_saved": "Saved",
      "save_state_could_not_save": "Could not save",
      "delete_note": "Delete this note?",
      "note_deleted": "Note deleted",
      "undo": "Undo",
      "photo": "Add photo",
      "photo_adding": "Adding photo…",
      "revisions": "Previous versions",
      "revisions_empty": "No previous versions yet.",
      "revisions_checkpoint": "Checkpoint",
      "revisions_diff_heading": "Preview",
      "restore": "Restore",
      "revision_restore_explanation":
          "Restoring makes this the current version. The version it replaces stays in history.",
      "sync": "Sync now",
      "server": "Synchronization server",
      "server_optional":
          "Optional. Your complete collection stays on this device.",
      "connection_code": "Connection code",
      "connection_code_hint":
          "Paste the connection code your server administrator shared (from a QR code or copied text). It already includes the server address, invite, and certificate verification.",
      "connect_with_code": "Connect with code",
      "advanced_server_setup": "Advanced connection setup",
      "server_url": "HTTPS server URL",
      "current_server": "Connected server",
      "connection_protocol": "Connection protocol",
      "protocol_https": "HTTPS / TLS 1.3",
      "certificate_verification": "Certificate verification",
      "invite_code": "Invite code (first connection)",
      "fingerprint": "SHA-256 certificate fingerprint",
      "pinned": "Pinned certificate",
      "trusted": "System-trusted certificate",
      "connect": "Connect",
      "apply_server_changes": "Apply server changes",
      "disconnect": "Disable server",
      "sync_status_label": "Sync status",
      "sync_status_local_only": "Local only",
      "sync_status_offline": "Offline, will retry",
      "sync_status_active": "Syncing…",
      "sync_status_current": "Up to date",
      "sync_status_pending": "Waiting to sync",
      "sync_status_retrying": "Retrying",
      "sync_status_action_required": "Action needed",
      "your_identity": "Your identity code",
      "your_identity_hint":
          "Send this code to the owner of a workspace you want to join.",
      "copy": "Copy",
      "copied": "Copied",
      "retry": "Retry",
      "sync_journal_title": "Unsafe incoming operations",
      "sync_journal_empty": "No unsafe incoming operations.",
      "sync_quarantine_reason_unsupported_version":
          "This operation uses a protocol version this device does not support yet.",
      "sync_quarantine_reason_verification_failed":
          "This operation could not be verified and may be corrupted.",
      "sync_quarantine_reason_empty_verified_operation":
          "This operation could not be processed.",
      "sync_quarantine_reason_op_id_reuse":
          "This operation reused an identifier with different content.",
      "sync_quarantine_reason_apply_failed":
          "This operation could not be applied to your local data.",
      "sync_quarantine_reason_unknown":
          "This operation could not be safely applied.",
      "share_workspace": "Share this workspace",
      "paste_identity": "Paste their identity code",
      "generate_share_code": "Continue",
      "join_workspace": "Join a shared workspace",
      "paste_grant": "Paste their grant code",
      "join": "Continue",
      "show_code_to_copy": "Show code to copy",
      "hide_code": "Hide code",
      "qr_alt_identity": "QR code for your identity",
      "qr_alt_grant": "QR code for the workspace access you generated",
      "share_confirm_title": "Give this device or person access?",
      "share_confirm_description":
          "They will be able to read and change every note in this workspace. You can disconnect them later from the device list.",
      "share_confirm_button": "Confirm and generate code",
      "share_success_title": "Ready to share.",
      "share_success_description":
          "Have them scan this code, or show the text version below.",
      "share_another": "Share with someone else",
      "join_confirm_title": "Join this workspace?",
      "join_confirm_description":
          "This becomes your active workspace. Your own notes stay on this device and are not deleted.",
      "join_confirm_button": "Confirm and join",
      "join_success_title": "You're connected.",
      "join_success_description":
          "This device now has access to the shared workspace.",
      "workspaces": "Workspaces",
      "workspace_owner": "Owner",
      "workspace_member": "Member",
      "workspace_members": "members",
      "share_import_summary": "shared items added to your notes",
      "workspace_active": "Active",
      "workspace_switch": "Switch",
      "workspace_sync_pending":
          "Workspace joined. Wait for synchronization to finish before opening its notes.",
      "devices_title": "Devices",
      "this_device": "This device",
      "device_local": "Local",
      "device_revoked": "Revoked",
      "device_disconnect_button": "Disconnect",
      "device_platform_windows": "Windows",
      "device_platform_android": "Android",
      "device_platform_unknown": "Unknown platform",
      "device_last_seen": "Last seen",
      "revoke_confirm_title": "Disconnect",
      "revoke_confirm_description":
          "This stops future synchronization for this device or person. It cannot erase notes or keys they already downloaded before now.",
      "revoke_confirm_button": "Disconnect",
      "lock": "Lock",
      "offline": "Changes save locally and will sync later.",
      "empty": "No notes yet",
      "title": "Title",
      "body": "Start writing…",
      "error": "Could not complete the action",
      "backup": "Encrypted backup",
      "backup_now": "Back up now",
      "backup_destination": "Choose destination",
      "backup_import": "Import from destination",
      "backup_empty": "No backups yet",
      "replace_restore": "Replace from backup",
      "restore_warning":
          "This verifies the backup, creates a safety backup, and replaces the local collection.",
      "restore_preview_title": "Backup contents",
      "restore_preview_empty": "This backup has no notes.",
      "restore_plan_title": "Restore preview",
      "restore_required_storage": "Space required",
      "restore_kind_addition": "New",
      "restore_kind_update": "Updated",
      "restore_kind_unchanged": "Unchanged",
      "restore_selected_button": "Restore selected as new notes",
      "restore_selected_success": "Notes restored",
      "restore_success": "Restore complete.",
      "close": "Close",
      "cancel": "Cancel",
      "settings": "Settings",
      "settings_group_general": "General",
      "settings_group_security": "Security",
      "settings_group_synchronization": "Synchronization",
      "settings_group_data": "Data",
      "settings_group_advanced": "Advanced",
      "settings_group_about": "About",
      "settings_general_empty": "No general settings on this device yet.",
      "settings_privacy_defaults":
          "Beresta enables no external product analytics, behavioral "
          "tracking, remote telemetry, or third-party crash upload by "
          "default.",
      "auto_lock": "Automatic lock",
      "attachment_photo": "Photo attachment",
      "attachment_file": "File attachment",
      "attachment_retention": "Downloaded attachments",
      "retention_all": "Keep all",
      "retention_selected": "Selected notebooks",
      "retention_metadata": "Metadata only",
      "cache_limit": "Cache limit (MiB)",
      "backup_capacity":
          "Not enough free space. Existing backups were not changed.",
      "backup_estimated_size": "Estimated size",
      "diagnostics_title": "Diagnostics",
      "diagnostics_app_version": "App version",
      "diagnostics_platform": "Platform",
      "diagnostics_sync_configured": "Server configured",
      "diagnostics_yes": "Yes",
      "diagnostics_no": "No",
      "diagnostics_last_successful_sync": "Last successful sync",
      "diagnostics_never": "Never",
      "diagnostics_pending_count": "Changes waiting to sync",
      "diagnostics_connection_state": "Connection state",
      "diagnostics_backup": "Backup",
      "diagnostics_storage_usage": "Local storage used",
      "diagnostics_database": "Database health",
      "diagnostics_update": "Update status",
      "diagnostics_show_technical_details": "Show technical details",
      "diagnostics_hide_technical_details": "Hide technical details",
      "diagnostics_copy": "Copy diagnostics",
      "diagnostics_copied": "Copied",
      "diagnostics_workspace_id": "Workspace ID",
      "diagnostics_device_id": "Device ID",
      "diagnostics_last_error_class": "Last synchronization error",
      "diagnostics_pending_operation_count": "Pending operations",
      "diagnostics_quarantined_operation_ids": "Unsafe operation IDs",
      "diagnostics_cursor": "Cursor",
      "diagnostics_retry_count": "Consecutive retry attempts",
      "diagnostics_retry_in": "Next retry in",
      "diagnostics_transport_protocol": "Transport protocol",
      "diagnostics_transport_security_mode": "Certificate verification",
      "diagnostics_transport_url": "Server URL",
      "diagnostics_migration_version": "Database schema version",
      "diagnostics_rotation_pending": "Workspace key rotation pending",
      "diagnostics_none": "None",
      "backup_health_healthy": "Healthy",
      "backup_health_warning": "Needs attention",
      "backup_health_corrupt": "Corrupt",
      "backup_health_unknown": "Not yet checked",
      "backup_last_verified": "Last verified",
      "backup_location": "Location",
      "backup_corrupt_explanation":
          "This backup failed verification and cannot be restored.",
      "database_health_ok": "Healthy",
      "database_health_degraded": "Needs attention",
      "database_health_unknown": "Not yet checked",
      "data_check_action": "Check my data",
      "data_check_issue_none": "No problems found.",
      "data_check_issue_search_index_repaired":
          "No problems found. A minor search index issue was automatically repaired.",
      "data_check_issue_backup_needs_attention":
          "Your backup needs attention. Create a new backup from Data settings.",
      "data_check_issue_database_needs_restore":
          "A local data problem was found. Restore from a backup in Data settings.",
      "update_status_up_to_date": "Up to date",
      "update_status_available": "Update available",
      "update_status_downloading": "Downloading update",
      "update_status_ready_to_install": "Ready to install",
      "update_status_failed": "Update failed",
      "update_status_unknown": "Not yet checked",
    },
    "ru": {
      "tagline": "Зашифрованные заметки доступны офлайн.",
      "create": "Создать локальный аккаунт",
      "unlock": "Разблокировать",
      "passphrase": "Парольная фраза",
      "device_unlock": "Разблокировать по биометрии или PIN-коду",
      "local_hint":
          "Аккаунт создаётся только на этом устройстве. Сервер необязателен.",
      "returning_hint":
          "Введите парольную фразу, чтобы разблокировать это устройство.",
      "sync_prompt_title": "Подключить сервер синхронизации?",
      "sync_prompt_description":
          "Можно подключить это устройство к собственному серверу синхронизации сейчас или пропустить этот шаг и сделать это позже в настройках — в любом случае локальные заметки не пострадают.",
      "sync_prompt_connect": "Подключить сейчас",
      "sync_prompt_skip": "Пропустить",
      "notes": "Заметки",
      "notebooks": "Блокноты",
      "new_notebook": "Новый блокнот",
      "more_actions": "Другие действия",
      "notebook_name": "Название блокнота",
      "create_action": "Создать",
      "rename": "Переименовать",
      "rename_notebook": "Переименовать блокнот",
      "delete": "Удалить",
      "delete_notebook": "Удалить блокнот?",
      "delete_notebook_warning":
          "Заметки внутри сохранятся и останутся видны в общем списке.",
      "notebook_has_children":
          "Сначала удалите или перенесите вложенные блокноты.",
      "tags": "Метки",
      "new_tag": "Новая метка",
      "tag_name": "Название метки",
      "add_tag": "Добавить метку",
      "move_to_notebook": "Переместить в блокнот",
      "no_notebook": "Без блокнота",
      "delete_photo": "Удалить это фото?",
      "delete_attachment": "Удалить это вложение?",
      "search": "Поиск заметок и фильтры",
      "new_note": "Новая заметка",
      "untitled": "Без названия",
      "save": "Сохранить",
      "save_state_saving": "Сохранение…",
      "save_state_saved": "Сохранено",
      "save_state_could_not_save": "Не удалось сохранить",
      "delete_note": "Удалить эту заметку?",
      "note_deleted": "Заметка удалена",
      "undo": "Отменить",
      "photo": "Добавить фото",
      "photo_adding": "Добавление фото…",
      "revisions": "Предыдущие версии",
      "revisions_empty": "Пока нет предыдущих версий.",
      "revisions_checkpoint": "Контрольная точка",
      "revisions_diff_heading": "Предпросмотр",
      "restore": "Восстановить",
      "revision_restore_explanation":
          "Восстановление сделает эту версию текущей. Заменённая версия останется в истории.",
      "sync": "Синхронизировать",
      "server": "Сервер синхронизации",
      "server_optional":
          "Необязательно. Полная коллекция останется на этом устройстве.",
      "connection_code": "Код подключения",
      "connection_code_hint":
          "Вставьте код подключения, который прислал администратор сервера (из QR-кода или скопированного текста). Он уже содержит адрес сервера, приглашение и проверку сертификата.",
      "connect_with_code": "Подключиться по коду",
      "advanced_server_setup": "Расширенная настройка подключения",
      "server_url": "HTTPS-адрес сервера",
      "current_server": "Подключённый сервер",
      "connection_protocol": "Протокол подключения",
      "protocol_https": "HTTPS / TLS 1.3 (защищённый)",
      "certificate_verification": "Проверка сертификата",
      "invite_code": "Код приглашения (первое подключение)",
      "fingerprint": "SHA-256 отпечаток сертификата",
      "pinned": "Закреплённый сертификат",
      "trusted": "Доверенный системой сертификат",
      "connect": "Подключить",
      "apply_server_changes": "Применить изменения сервера",
      "disconnect": "Отключить сервер",
      "sync_status_label": "Статус синхронизации",
      "sync_status_local_only": "Только локально",
      "sync_status_offline": "Нет соединения, повтор позже",
      "sync_status_active": "Синхронизация…",
      "sync_status_current": "Синхронизировано",
      "sync_status_pending": "Ожидает синхронизации",
      "sync_status_retrying": "Повтор попытки",
      "sync_status_action_required": "Требуется действие",
      "your_identity": "Ваш код идентификации",
      "your_identity_hint":
          "Отправьте этот код владельцу пространства, к которому хотите присоединиться.",
      "copy": "Копировать",
      "copied": "Скопировано",
      "retry": "Повторить",
      "sync_journal_title": "Небезопасные входящие операции",
      "sync_journal_empty": "Нет небезопасных входящих операций.",
      "sync_quarantine_reason_unsupported_version":
          "Эта операция использует версию протокола, которую это устройство пока не поддерживает.",
      "sync_quarantine_reason_verification_failed":
          "Эту операцию не удалось проверить, возможно, она повреждена.",
      "sync_quarantine_reason_empty_verified_operation":
          "Эту операцию не удалось обработать.",
      "sync_quarantine_reason_op_id_reuse":
          "Эта операция повторно использует идентификатор с другим содержимым.",
      "sync_quarantine_reason_apply_failed":
          "Эту операцию не удалось применить к локальным данным.",
      "sync_quarantine_reason_unknown":
          "Эту операцию не удалось безопасно применить.",
      "share_workspace": "Поделиться этим пространством",
      "paste_identity": "Вставьте их код идентификации",
      "generate_share_code": "Продолжить",
      "join_workspace": "Присоединиться к общему пространству",
      "paste_grant": "Вставьте их код доступа",
      "join": "Продолжить",
      "show_code_to_copy": "Показать код для копирования",
      "hide_code": "Скрыть код",
      "qr_alt_identity": "QR-код вашей идентификации",
      "qr_alt_grant": "QR-код созданного доступа к пространству",
      "share_confirm_title":
          "Предоставить доступ этому устройству или человеку?",
      "share_confirm_description":
          "Они смогут читать и изменять все заметки в этом пространстве. Позже вы сможете отключить их в списке устройств.",
      "share_confirm_button": "Подтвердить и создать код",
      "share_success_title": "Готово к передаче.",
      "share_success_description":
          "Попросите отсканировать этот код или покажите текстовую версию ниже.",
      "share_another": "Поделиться ещё с кем-то",
      "join_confirm_title": "Присоединиться к этому пространству?",
      "join_confirm_description":
          "Оно станет вашим активным пространством. Ваши собственные заметки останутся на этом устройстве и не будут удалены.",
      "join_confirm_button": "Подтвердить и присоединиться",
      "join_success_title": "Вы подключены.",
      "join_success_description":
          "Это устройство теперь имеет доступ к общему пространству.",
      "workspaces": "Рабочие пространства",
      "workspace_owner": "Владелец",
      "workspace_member": "Участник",
      "workspace_members": "участников",
      "share_import_summary": "публикаций из «Поделиться» добавлено в заметки",
      "workspace_active": "Активно",
      "workspace_switch": "Переключить",
      "workspace_sync_pending":
          "Пространство подключено. Дождитесь завершения синхронизации перед открытием заметок.",
      "devices_title": "Устройства",
      "this_device": "Это устройство",
      "device_local": "Локальное",
      "device_revoked": "Отозвано",
      "device_disconnect_button": "Отключить",
      "device_platform_windows": "Windows",
      "device_platform_android": "Android",
      "device_platform_unknown": "Платформа неизвестна",
      "device_last_seen": "Последняя активность",
      "revoke_confirm_title": "Отключить",
      "revoke_confirm_description":
          "Это прекращает будущую синхронизацию для этого устройства или человека. Это не может стереть заметки или ключи, уже загруженные ими ранее.",
      "revoke_confirm_button": "Отключить",
      "lock": "Заблокировать",
      "offline": "Изменения сохранятся локально и синхронизируются позже.",
      "empty": "Заметок пока нет",
      "title": "Заголовок",
      "body": "Начните писать…",
      "error": "Не удалось выполнить действие",
      "backup": "Зашифрованная копия",
      "backup_now": "Создать копию",
      "backup_destination": "Выбрать хранилище",
      "backup_import": "Импортировать из хранилища",
      "backup_empty": "Копий пока нет",
      "replace_restore": "Заменить из копии",
      "restore_warning":
          "Копия будет проверена, затем Береста создаст страховочную копию и заменит локальную коллекцию.",
      "restore_preview_title": "Содержимое копии",
      "restore_preview_empty": "В этой копии нет заметок.",
      "restore_plan_title": "Предпросмотр восстановления",
      "restore_required_storage": "Требуется места",
      "restore_kind_addition": "Новая",
      "restore_kind_update": "Изменена",
      "restore_kind_unchanged": "Без изменений",
      "restore_selected_button": "Восстановить выбранное как новые заметки",
      "restore_selected_success": "Заметки восстановлены",
      "restore_success": "Восстановление завершено.",
      "close": "Закрыть",
      "cancel": "Отмена",
      "settings": "Настройки",
      "settings_group_general": "Общие",
      "settings_group_security": "Безопасность",
      "settings_group_synchronization": "Синхронизация",
      "settings_group_data": "Данные",
      "settings_group_advanced": "Дополнительно",
      "settings_group_about": "О программе",
      "settings_general_empty": "На этом устройстве пока нет общих настроек.",
      "settings_privacy_defaults":
          "По умолчанию Beresta не использует внешнюю аналитику продукта, "
          "отслеживание поведения, удалённую телеметрию и отправку "
          "отчётов о сбоях сторонним сервисам.",
      "auto_lock": "Автоматическая блокировка",
      "attachment_photo": "Фотовложение",
      "attachment_file": "Файловое вложение",
      "attachment_retention": "Загруженные вложения",
      "retention_all": "Хранить все",
      "retention_selected": "Выбранные блокноты",
      "retention_metadata": "Только метаданные",
      "cache_limit": "Лимит кэша (МиБ)",
      "backup_capacity":
          "Недостаточно свободного места. Существующие копии не изменены.",
      "backup_estimated_size": "Примерный размер",
      "diagnostics_title": "Диагностика",
      "diagnostics_app_version": "Версия приложения",
      "diagnostics_platform": "Платформа",
      "diagnostics_sync_configured": "Сервер настроен",
      "diagnostics_yes": "Да",
      "diagnostics_no": "Нет",
      "diagnostics_last_successful_sync": "Последняя успешная синхронизация",
      "diagnostics_never": "Никогда",
      "diagnostics_pending_count": "Изменений ожидает синхронизации",
      "diagnostics_connection_state": "Состояние соединения",
      "diagnostics_backup": "Резервная копия",
      "diagnostics_storage_usage": "Используется локального хранилища",
      "diagnostics_database": "Состояние базы данных",
      "diagnostics_update": "Состояние обновления",
      "diagnostics_show_technical_details": "Показать технические детали",
      "diagnostics_hide_technical_details": "Скрыть технические детали",
      "diagnostics_copy": "Скопировать диагностику",
      "diagnostics_copied": "Скопировано",
      "diagnostics_workspace_id": "ID пространства",
      "diagnostics_device_id": "ID устройства",
      "diagnostics_last_error_class": "Последняя ошибка синхронизации",
      "diagnostics_pending_operation_count": "Ожидающих операций",
      "diagnostics_quarantined_operation_ids": "ID небезопасных операций",
      "diagnostics_cursor": "Курсор",
      "diagnostics_retry_count": "Подряд неудачных попыток",
      "diagnostics_retry_in": "Следующая попытка через",
      "diagnostics_transport_protocol": "Протокол передачи",
      "diagnostics_transport_security_mode": "Проверка сертификата",
      "diagnostics_transport_url": "URL сервера",
      "diagnostics_migration_version": "Версия схемы базы данных",
      "diagnostics_rotation_pending":
          "Смена ключа рабочего пространства ожидает завершения",
      "diagnostics_none": "Нет",
      "backup_health_healthy": "В порядке",
      "backup_health_warning": "Требует внимания",
      "backup_health_corrupt": "Повреждена",
      "backup_health_unknown": "Ещё не проверена",
      "backup_last_verified": "Последняя проверка",
      "backup_location": "Хранилище",
      "backup_corrupt_explanation":
          "Эта копия не прошла проверку и не может быть восстановлена.",
      "database_health_ok": "В порядке",
      "database_health_degraded": "Требует внимания",
      "database_health_unknown": "Ещё не проверена",
      "data_check_action": "Проверить мои данные",
      "data_check_issue_none": "Проблем не найдено.",
      "data_check_issue_search_index_repaired":
          "Проблем не найдено. Небольшая неполадка поиска была устранена автоматически.",
      "data_check_issue_backup_needs_attention":
          "Резервная копия требует внимания. Создайте новую копию в разделе «Данные».",
      "data_check_issue_database_needs_restore":
          "Обнаружена проблема с локальными данными. Восстановите их из резервной копии в разделе «Данные».",
      "update_status_up_to_date": "Установлена последняя версия",
      "update_status_available": "Доступно обновление",
      "update_status_downloading": "Загрузка обновления",
      "update_status_ready_to_install": "Готово к установке",
      "update_status_failed": "Ошибка обновления",
      "update_status_unknown": "Ещё не проверено",
    },
  };

  String call(String key) =>
      values[language]?[key] ?? values["en"]![key] ?? key;
}
